dev-dependencies = { }

[package]
name = "sui"
version = "0.2.0"
description = "SUI blockchain library for Internet Computer"
repository = "https://github.com/codecustard/sui"
keywords = [ "sui", "blockchain", "chain-fusion", "crypto" ]
license = "MIT"

[dependencies]
base = "0.16.0"
hex = "1.0.2"
blake2b = "0.1.0"
ic = "3.2.0"
json = "1.4.0"
base-x-encoder = "2.1.0"
sha3 = "0.1.1"
sha2 = "0.1.9"
bcs = "0.1.3"
